### PR TITLE
Bump ABACUS version to 3.1.1

### PR DESCRIPTION
**Pull request by caic99**

### CODE REVIEW

**Comment by caic99** [comment]
https://github.com/deepmodeling/abacus-develop/pull/1821

**Comment by njzjz** [comment]
Instead you can add a patch:
https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#patches

The patch file can be directly downloaded from https://github.com/deepmodeling/abacus-develop/pull/1821.patch

**Comment by caic99** [comment]
@njzjz Thanks! But it seems that conda-build does not take a url for the patch file, and this means I have to download this file before building it? Maybe we could just leave this patch to the next release.

**Comment by njzjz** [comment]
> this means I have to download this file before building it

Yes, and add it to `recipe` directory.

**Pull request merged**
